export const genres = [
   'Ação',
   'Demônios',
   'Horror',
   'Isekai',
   'Romance',
   'Shounen',
   'Comédia',
   'Seinen',
   'Psicológico',
   'Sobrenatural',
   'Aventura',
   'Tragédia',
   'Suspense',
   'Super Poderes',
   'Mistério',
   'Fantasia',
   'Drama',
   'Magia',
   'Jogos',
   'Samurai',
   'Sci-Fi',
   'Vampiros',
   'Slice of Life',
   'Demência',
   'Shoujo',
   'Shoujo Ai',
   'Yaoi',
   'Yuri',
   'Doujinshi',
   'Escolar',
   'Espacial',
   'Esportes',
   'Fanzine',
   'Gastronomia',
   'Genérico',
   'Harém',
   'Histórico',
   'Josei',
   'Light Novel',
   'Manhua',
   'Mechas',
   'Militar',
   'Música',
   'One Shot',
   'Paródia',
   'Policial',
]
